---
title: "Corn Futures"
author: "Santiago Orantes"
date: "5/12/2021"
output: pdf_document
urlcolor: blue
---

# Continuous Futures (Quandl)

[Link to Quandl Continuous Futures](https://data.nasdaq.com/data/CHRIS-wiki-continuous-futures/documentation)

## Continuous Contracts  

Individual futures contracts trade for very short periods of time and are hence unsuitable for long-horizon analysis. Continuous futures contracts solve this problem by chaining together a series of individual futures contracts, to provide a long-term price history that is suitable for trading, behavioral and strategy analysis.

### Contract Numbering (depth)  

The advantage of continuous contract numbering is that it allows traders and analysts to construct very long historical time series of futures data for particular commodities. For example, C1 (Front Corn) data goes all the way back to 1970, even though no individual Corn contract is active for more than a year or two.

#### Format of the Contract  
* CHRIS/{EXCHANGE}_{CODE}{NUMBER}  

where {NUMBER} is the "depth" associated with the chained contract. For instance, the front month contract has depth 1, the second month contract has depth 2, and so on.


# Corn Futures

[Contract Specs](https://www.cmegroup.com/markets/agriculture/oilseeds/corn.contractSpecs.html)  
[Corn Settlements](https://www.cmegroup.com/confluence/display/EPICSANDBOX/Corn)  
[Corn Calendar](https://www.cmegroup.com/markets/agriculture/oilseeds/corn.calendar.html)

* **Listed Contracts**: There are **9 monthly contracts** of **March, May** and **September** and  **8 monthly** contracts of  **July** and **December** listed annually after the termination of the trading in the December contract of the current year. Trading **terminates** on the business day prior to the **15th day** of the **contract month**.

* **Contract Unit**: 5,000 bushels.

* **Price Quotation**: USD cents per bushel. 

* **Bushel / Tonne**: 1 Tonne = 39.368 Bushels.

In the case of **corn** in the Mexican state of **Sinaloa**, the dates of **plantation** (sow) range from **01/10 (October 1st) to 31/12 (December 31st)** while the dates of **harvest** range from **15/04 (April 15th) to 15/07 (July 15th)**. 

Common practice to determine the **price** at the time of **plantation** is to use the **average price**, of the reference futures contract, for the **month prior to plantation**. Similarly, the **price** at the time of **harvest** is based on the **average price of the reference futures contract** for the **month prior to the end of the reference contract (or harvest)**.

So in our corn example, depending on the dates of plantation and harvest of the farmers we would estimate the price of  plantation and the price of harvest:

Assume a farmer plants at the very last date and harvests at the very last date, then we would have:

* Price at plantation (base price) is the average price in December of the futures contract of July.
* Price at Harvest (harvest price) is the average price from June-15th to July-15th of the July contract.

Obviously as the maturity of the contract approaches, the price of the underlying converges to the true price that will be paid.

According to [SIAP](http://infosiap.siap.gob.mx:8080/agricola_siap_gobmx/ResumenProducto.do) data, almost all of the **harvest** of **Corn_Autum-Winter_irrigation_Sinaloa** happens in the months of **May** and **June**.



