---
title: "Optimal Premium Rate"
subtitle: "Yield and Revenue Insurance"
author: "Santiago Orantes"
date: "5/1/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Yield Insurance  

Consider an insurance contract that will pay indemnities ($I$) when the yield falls below a certain proportion $\lambda$ of the expected insured yield $\mu$ at an agreed price $P$:

$$I=P\cdot(\max\{\lambda\mu-y, 0\})$$

For simplicity assume 2 states of nature: *loss* with probability $p$ and *no loss* with prob $1-p$.  

Then the farmer chooses a contract that maximizes his expected utility:

$$\mathcal{U}(\cdot)=(1-p)\cdot \mathcal{U}(m-\pi)+p\cdot\mathcal{U}(m-\pi-d+I)$$

where,

* $\mathcal{U}(\cdot)$ denotes the Von Neuman-Morgenstern utility function (strictly increasing, strictly concave and twice differentiable).
* $m$ is the initial income.
* $\pi$ is the premium. 
* $d$ is the loss.

Let $\alpha$ be a continuous r.v. denoting the insurance contract. We can express both the premium and the indemnity as a function of the insurance contract i.e. $I=I(\alpha)$ and $\pi =\pi(\alpha)$.

Taking First Order Conditions (FOC) we get that the optimal choice of insurance contract for the farmer is:

$$
\frac{\mathcal{U}^{'}(m-\pi)}{\mathcal{U}^{'}(m-\pi(\alpha)-d+I(\alpha))}=\frac{p\left(I^{'}(\alpha)-\pi^{'}(\alpha)\right)}{(1-p)\pi^{'}(\alpha)}
$$








